### ISSUE TITLE
Getting this exception : ImportError: cannot import name getcwd

### ISSUE THREAD

**Issue by moun3imy** [bhrigu123/classifier#69]
I get this exception when trying to run the script on my Downloads folder

> Traceback (most recent call last):
>   File "/usr/local/bin/classifier", line 7, in <module>
>     from classifier.classifier import main
>   File "/Library/Python/2.7/site-packages/classifier/classifier.py", line 8, in <module>
>     from six.moves import getcwd
> ImportError: cannot import name getcwd

**Comment by bhrigu123** [comment]
What version of the python package `six` do you have?
(check by running `pip freeze` and look for 'six' )
You must be having a version>=1.10.0 of 'six' for this to run.

**Comment by moun3imy** [comment]
I have the 1.10.0 version of _six_

**Comment by bhrigu123** [comment]
Oh, that's weird. Why isn't it able to import `getcwd` ?
Try running python on your shell and run:
`import six`
`from six.moves import getcwd`
`getcwd()`

To see if it is importing getcwd. Also check you have proper version of `six` for python3 (pip3) just in case.

**Comment by moun3imy** [comment]
I'm using python 2.7.11, I tried runnning that script and it's giving no error  neither printing anything :)

**Comment by bhrigu123** [comment]
That's really odd. I just installed and tested on a new comp. and it's working fine.
How is it that a python is unable to import getcwd from the file, and while testing on shell it is importing.

You could try re-installing (try installing with `sudo` if you didn't earlier).....and also try on a different computer if you can, just for testing....and see if it is working then or not.
