### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'arrow' 

### ISSUE THREAD

**Issue by killown** [bhrigu123/classifier#76]
➜  Downloads classifier
Traceback (most recent call last):
  File "/usr/bin/classifier", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'arrow' distribution was not found and is required by classifier

**Comment by bhrigu123** [comment]
I think `arrow` did not get installed for you. Could be because of older version of pip, not sure.

You can try installing `arrow` separately. 
`pip install arrow`
For python3: `pip3 install arrow`

I think it is trying to run from python3 in your case.
